import {frontLabels,sideLabels,measure,scale} from './engine.mjs';
const $=id=>document.getElementById(id),canvas=$('canvas'),ctx=canvas.getContext('2d');
const fresh=()=>({front:{image:null,points:[],referenceCm:100},side:{image:null,points:[],referenceCm:100}});
let data=fresh(),stream=null,results=[],busy=false;
const current=()=>data[$('view').value],labels=()=>$('view').value==='front'?frontLabels:sideLabels;
function stop(){stream?.getTracks().forEach(t=>t.stop());stream=null;$('video').srcObject=null;$('video').hidden=true;$('capture').disabled=true;}
function invalidate(){results=[];$('results').replaceChildren();$('export').disabled=true;}
function message(s){$('message').textContent=s;}
function draw(){const d=current();canvas.hidden=!d.image;if(!d.image)return;canvas.width=d.image.width;canvas.height=d.image.height;ctx.drawImage(d.image,0,0);const r=Math.max(5,canvas.width/130);d.points.forEach((p,i)=>{ctx.beginPath();ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.fillStyle='#d4ea9b';ctx.fill();ctx.fillStyle='#091921';ctx.font=`bold ${r*2}px sans-serif`;ctx.fillText(i+1,p.x+r,p.y-r);});}
function refresh(){const d=current(),ls=labels();$('reference').value=d.referenceCm;$('edit').replaceChildren(new Option('Next unmarked point',''));ls.forEach((l,i)=>{if(d.points[i])$('edit').add(new Option(`${i+1}. ${l}`,String(i)));});$('guide').textContent=d.image?(d.points.length<ls.length?`Tap ${d.points.length+1}: ${ls[d.points.length]}`:'All points marked. Review using Edit point, then switch views.'):`Capture or load your ${$('view').value} photograph.`;$('progress').textContent=`Front ${data.front.points.length}/${frontLabels.length} · Side ${data.side.points.length}/${sideLabels.length}`;draw();}
function setImage(img){stop();current().image=img;current().points=[];invalidate();message('Mark landmarks on the photograph.');refresh();}
$('start').onclick=async()=>{if(busy)return;busy=true;stop();try{if(!navigator.mediaDevices?.getUserMedia)throw Error('Camera requires HTTPS or localhost. You can also load a photo.');stream=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:2560}}});$('video').srcObject=stream;$('video').hidden=false;canvas.hidden=true;await $('video').play();$('capture').disabled=false;message('Keep camera level. Capture when your full body and reference are visible.');}catch(e){stop();message(e.message);}finally{busy=false;}};
$('capture').onclick=()=>{const v=$('video');if(!v.videoWidth)return message('Wait for the camera image.');const image=document.createElement('canvas');image.width=v.videoWidth;image.height=v.videoHeight;image.getContext('2d').drawImage(v,0,0);setImage(image);};
$('upload').onchange=async e=>{const file=e.target.files[0];if(!file)return;const view=$('view').value;try{if(file.size>20*1024*1024)throw Error('Choose an image below 20 MB.');const img=await createImageBitmap(file);if(view!==$('view').value){img.close();throw Error('View changed while loading. Select the image again.');}setImage(img);}catch(e){message('Could not load photo: '+e.message);}e.target.value='';};
canvas.onpointerdown=e=>{if(!current().image)return;const box=canvas.getBoundingClientRect();const p={x:(e.clientX-box.left)*canvas.width/box.width,y:(e.clientY-box.top)*canvas.height/box.height};const selection=$('edit').value,index=selection===''?current().points.length:Number(selection);if(index>=labels().length)return;current().points[index]=p;invalidate();refresh();};
$('edit').onchange=()=>{const i=$('edit').value;if(i!=='')$('guide').textContent=`Tap replacement for ${labels()[Number(i)]}`;};
$('view').onchange=()=>{stop();message('');refresh();};
$('reference').oninput=()=>{current().referenceCm=Number($('reference').value);invalidate();};
$('undo').onclick=()=>{current().points.pop();invalidate();refresh();};
$('clearView').onclick=()=>{stop();current().image?.close?.();current().image=null;current().points=[];invalidate();refresh();};
function render(){const unit=$('units').value;$('results').replaceChildren();for(const r of results){const tr=document.createElement('tr');for(const text of [r.name,`${(r.cm/(unit==='in'?2.54:1)).toFixed(1)} ${unit}`,`${r.method}. ${r.status}.`]){const td=document.createElement('td');td.textContent=text;tr.append(td);}$('results').append(tr);}}
$('calculate').onclick=()=>{try{results=measure(data.front,data.side);render();$('export').disabled=false;message('Estimates calculated. Displayed decimals do not indicate measurement accuracy.');}catch(e){invalidate();message(e.message);}};
$('units').onchange=render;
$('export').onclick=()=>{if(!results.length)return;const payload={schemaVersion:1,createdAt:new Date().toISOString(),accuracy:'Unvalidated; no established error bound',definitions:'Lengths are straight projected distances. Circumferences use an ellipse approximation. No garment ease included.',calibration:{frontCmPerPixel:scale(data.front.points,data.front.referenceCm),sideCmPerPixel:scale(data.side.points,data.side.referenceCm)},measurements:results};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='riel-body-measurements.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('reset').onclick=()=>{stop();Object.values(data).forEach(d=>d.image?.close?.());data=fresh();invalidate();message('Session deleted.');refresh();};
window.addEventListener('pagehide',stop);document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});refresh();
